run:
  timeout: 5m
  tests: true
  skip-dirs:
    - docs
    - bin
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jonosize/affiliate-platform

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
    - linters:
        - typecheck
      text: "undefined: echo"
    - linters:
        - typecheck
      text: "undefined: cron"