// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/worker/refresh-prices": {
            "post": {
                "description": "Manually triggers the price refresh worker to update all product prices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Manually trigger price refresh job",
                "responses": {
                    "200": {
                        "description": "Price refresh triggered successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/campaigns": {
            "get": {
                "description": "Get a list of all campaigns with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Get all campaigns",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Campaigns retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CampaignResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new marketing campaign with UTM parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Create a new campaign",
                "parameters": [
                    {
                        "description": "Campaign creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Campaign created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.CampaignResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/campaigns/{id}": {
            "delete": {
                "description": "Delete a campaign and all related data (campaign products, links, clicks)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Delete a campaign",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Campaign ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Campaign deleted successfully"
                    },
                    "400": {
                        "description": "Invalid campaign ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/campaigns/{id}/public": {
            "get": {
                "description": "Get campaign details with products and offers for public landing page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get public campaign details",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Campaign ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Campaign details retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.CampaignPublicResponse"
                        }
                    },
                    "400": {
                        "description": "Campaign is not active",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard": {
            "get": {
                "description": "Get aggregated click statistics, CTR, and top-performing products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get dashboard statistics",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Filter by campaign ID",
                        "name": "campaign_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marketplace (lazada or shopee)",
                        "name": "marketplace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date filter (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dashboard statistics retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.DashboardStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/links": {
            "post": {
                "description": "Generate a short affiliate link for a product/marketplace combination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Generate affiliate short link",
                "parameters": [
                    {
                        "description": "Link creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Link created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.LinkResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Product or campaign not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "description": "Get a list of all products with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Products retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ProductResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new product by fetching data from marketplace URL or SKU",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Add product from Lazada/Shopee URL or SKU",
                "parameters": [
                    {
                        "description": "Product creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/{id}": {
            "delete": {
                "description": "Delete a product and all related data (offers, links, campaign associations, clicks)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Product deleted successfully"
                    },
                    "400": {
                        "description": "Invalid product ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/{id}/offers": {
            "get": {
                "description": "Get all marketplace offers for a specific product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get offers (prices) for a product",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product offers retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductOffersResponse"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/go/{short_code}": {
            "get": {
                "description": "Redirects to the target marketplace URL and tracks the click event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Redirect to marketplace product URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Short code",
                        "name": "short_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to target URL"
                    },
                    "400": {
                        "description": "Invalid redirect URL",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Link not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BestPrice": {
            "type": "object",
            "properties": {
                "marketplace": {
                    "type": "string",
                    "example": "shopee"
                },
                "price": {
                    "type": "number",
                    "example": 279
                }
            }
        },
        "dto.CampaignProduct": {
            "type": "object",
            "properties": {
                "best_price": {
                    "$ref": "#/definitions/dto.BestPrice"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "links": {
                    "description": "Links for this product in the campaign",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProductLink"
                    }
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OfferResponse"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Product Title"
                }
            }
        },
        "dto.CampaignPublicResponse": {
            "type": "object",
            "properties": {
                "end_at": {
                    "type": "string",
                    "example": "2025-08-31T23:59:59Z"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "Summer Deal 2025"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CampaignProduct"
                    }
                },
                "start_at": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                }
            }
        },
        "dto.CampaignResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "end_at": {
                    "type": "string",
                    "example": "2025-08-31T23:59:59Z"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "Summer Deal 2025"
                },
                "start_at": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "utm_campaign": {
                    "type": "string",
                    "example": "summer_2025"
                }
            }
        },
        "dto.CampaignStat": {
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "campaign_name": {
                    "type": "string",
                    "example": "Summer Deal 2025"
                },
                "clicks": {
                    "type": "integer",
                    "example": 450
                }
            }
        },
        "dto.CreateCampaignRequest": {
            "type": "object",
            "required": [
                "end_at",
                "name",
                "start_at",
                "utm_campaign"
            ],
            "properties": {
                "end_at": {
                    "type": "string",
                    "example": "2025-08-31T23:59:59Z"
                },
                "name": {
                    "type": "string",
                    "example": "Summer Deal 2025"
                },
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"123e4567-e89b-12d3-a456-426614174000\"]"
                    ]
                },
                "start_at": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "utm_campaign": {
                    "type": "string",
                    "example": "summer_2025"
                }
            }
        },
        "dto.CreateLinkRequest": {
            "type": "object",
            "required": [
                "campaign_id",
                "marketplace",
                "product_id"
            ],
            "properties": {
                "campaign_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "marketplace": {
                    "type": "string",
                    "enum": [
                        "lazada",
                        "shopee"
                    ],
                    "example": "lazada"
                },
                "product_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "dto.CreateProductRequest": {
            "type": "object",
            "required": [
                "source",
                "sourceType"
            ],
            "properties": {
                "source": {
                    "type": "string",
                    "example": "https://www.lazada.co.th/products/example-i123456.html"
                },
                "sourceType": {
                    "type": "string",
                    "enum": [
                        "url",
                        "sku"
                    ],
                    "example": "url"
                }
            }
        },
        "dto.DashboardStatsResponse": {
            "type": "object",
            "properties": {
                "campaign_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CampaignStat"
                    }
                },
                "ctr": {
                    "description": "Click-through rate (percentage)",
                    "type": "number",
                    "example": 2.78
                },
                "marketplace_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MarketplaceStat"
                    }
                },
                "top_products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TopProduct"
                    }
                },
                "total_clicks": {
                    "type": "integer",
                    "example": 1250
                },
                "total_links": {
                    "type": "integer",
                    "example": 45
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string",
                    "example": "Error Type"
                },
                "message": {
                    "type": "string",
                    "example": "Human-readable message"
                }
            }
        },
        "dto.LinkResponse": {
            "type": "object",
            "properties": {
                "full_url": {
                    "type": "string",
                    "example": "https://demo.jonosize.com/go/abc123xyz"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "short_code": {
                    "type": "string",
                    "example": "abc123xyz"
                },
                "target_url": {
                    "type": "string",
                    "example": "https://www.lazada.co.th/products/...?utm_source=...\u0026utm_medium=affiliate\u0026utm_campaign=summer_2025"
                }
            }
        },
        "dto.MarketplaceStat": {
            "type": "object",
            "properties": {
                "clicks": {
                    "type": "integer",
                    "example": 750
                },
                "marketplace": {
                    "type": "string",
                    "example": "lazada"
                },
                "percentage": {
                    "type": "number",
                    "example": 60
                }
            }
        },
        "dto.OfferResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "last_checked_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "marketplace": {
                    "type": "string",
                    "example": "lazada"
                },
                "price": {
                    "type": "number",
                    "example": 299
                },
                "store_name": {
                    "type": "string",
                    "example": "Store Name"
                }
            }
        },
        "dto.ProductLink": {
            "type": "object",
            "properties": {
                "full_url": {
                    "type": "string",
                    "example": "https://demo.jonosize.com/go/abc123xyz"
                },
                "marketplace": {
                    "type": "string",
                    "example": "lazada"
                },
                "short_code": {
                    "type": "string",
                    "example": "abc123xyz"
                }
            }
        },
        "dto.ProductOffersResponse": {
            "type": "object",
            "properties": {
                "best_price": {
                    "$ref": "#/definitions/dto.BestPrice"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OfferResponse"
                    }
                },
                "product_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "dto.ProductResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OfferResponse"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Product Title"
                }
            }
        },
        "dto.TopProduct": {
            "type": "object",
            "properties": {
                "clicks": {
                    "type": "integer",
                    "example": 120
                },
                "marketplace": {
                    "type": "string",
                    "example": "lazada"
                },
                "product_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "product_name": {
                    "type": "string",
                    "example": "Product Title"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Jenosize Affiliate Platform API",
	Description:      "API for affiliate link generation and price comparison",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
